name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/src/services/api/最強タスク管理ツール/sales-task-core/**'
      - 'firebase.json'
      - '.firebaserc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALES_TASK_MANAGER_AF356 }}'
        channelId: live
        projectId: sales-task-manager-af356
        entryPoint: ./